services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextdb
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:
